update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -180,16 +180,20 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
-      - name: Verify Docker Images
+      - name: Debug Docker Image Outputs
         run: |
-          echo "Verifying Docker Image: ${{ needs.build.outputs.docker-image }}"
-          echo "Verifying DB Image: ${{ needs.build.outputs.db-image }}"
+          echo "Docker Images: ${{ needs.build.outputs.docker-image }}"
+          echo "DB Images: ${{ needs.build.outputs.db-image }}"
+      # - name: Verify Docker Images
+      #   run: |
+      #     echo "Verifying Docker Image: ${{ needs.build.outputs.docker-image }}"
+      #     echo "Verifying DB Image: ${{ needs.build.outputs.db-image }}"
           
-          # Verify if Docker images are accessible
-          docker pull ${{ needs.build.outputs.docker-image }} || { echo "Docker image not found!"; exit 1; }
-          docker pull ${{ needs.build.outputs.db-image }} || { echo "DB image not found!"; exit 1; }
+      #     # Verify if Docker images are accessible
+      #     docker pull ${{ needs.build.outputs.docker-image }} || { echo "Docker image not found!"; exit 1; }
+      #     docker pull ${{ needs.build.outputs.db-image }} || { echo "DB image not found!"; exit 1; }
           
-          echo "Both Docker images are accessible."
+      #     echo "Both Docker images are accessible."
 
 
   #     - name: Checkout Repository
